name: Check missing packages

on:
  schedule:
    - cron: "0 19 * * 0" # run at 4 AM JST on Sundays
  workflow_dispatch:

jobs:
  check-missing-packages:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - { ros_distribution: galactic, package: __dummy__ }

    container: ros:${{ matrix.ros_distribution }}

    steps:
      - name: Run apt-get update
        run: |
          sudo apt-get -y update

      - name: Check ros-${{ matrix.ros_distribution }}-${{ matrix.package }}
        run: |
          result=$(apt-cache search ros-${{ matrix.ros_distribution }}-${{ matrix.package }})
          if [ "$result" != "" ]; then
            sudo apt-get -y -q install ros-${{ matrix.ros_distribution }}-${{ matrix.package }} >/dev/null
            echo "${{ matrix.package }} is successfully installed. We can remove it from repos file."
            exit 1
          fi
